FROM quay.io/keycloak/keycloak:26.2.0

COPY seat-reservation-render-realm.json /opt/keycloak/data/import/seat-reservation-realm.json

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start", "--import-realm"]